In [6]:
from sklearn.datasets import load_iris# 加载数据集

iris = load_iris()
X = iris.data# 数据集特征
y = iris.target# 标签

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# 留出法

In [ ]:
from sklearn.model_selection import train_test_split# 导入train_test_split函数
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# 划分训练集和测试集，test_size=0.2表示测试集占20%，random_state=42表示随机数种子为42，保证每次划分的结果相同

查看结果

In [11]:
import pandas as pd
pd.DataFrame(X_train)

       0    1    2    3
0    4.6  3.6  1.0  0.2
1    5.7  4.4  1.5  0.4
2    6.7  3.1  4.4  1.4
3    4.8  3.4  1.6  0.2
4    4.4  3.2  1.3  0.2
..   ...  ...  ...  ...
115  6.1  2.8  4.0  1.3
116  4.9  2.5  4.5  1.7
117  5.8  4.0  1.2  0.2
118  5.8  2.6  4.0  1.2
119  7.1  3.0  5.9  2.1

[120 rows x 4 columns]

In [12]:
pd.DataFrame(X_test)

      0    1    2    3
0   6.1  2.8  4.7  1.2
1   5.7  3.8  1.7  0.3
2   7.7  2.6  6.9  2.3
3   6.0  2.9  4.5  1.5
4   6.8  2.8  4.8  1.4
5   5.4  3.4  1.5  0.4
6   5.6  2.9  3.6  1.3
7   6.9  3.1  5.1  2.3
8   6.2  2.2  4.5  1.5
9   5.8  2.7  3.9  1.2
10  6.5  3.2  5.1  2.0
11  4.8  3.0  1.4  0.1
12  5.5  3.5  1.3  0.2
13  4.9  3.1  1.5  0.1
14  5.1  3.8  1.5  0.3
15  6.3  3.3  4.7  1.6
16  6.5  3.0  5.8  2.2
17  5.6  2.5  3.9  1.1
18  5.7  2.8  4.5  1.3
19  6.4  2.8  5.6  2.2
20  4.7  3.2  1.6  0.2
21  6.1  3.0  4.9  1.8
22  5.0  3.4  1.6  0.4
23  6.4  2.8  5.6  2.1
24  7.9  3.8  6.4  2.0
25  6.7  3.0  5.2  2.3
26  6.7  2.5  5.8  1.8
27  6.8  3.2  5.9  2.3
28  4.8  3.0  1.4  0.3
29  4.8  3.1  1.6  0.2

# 交叉验证法
交叉验证法的原理是将数据集分成k份，每次使用k-1份训练模型，最后使用1份测试模型，重复k次，最后取平均值
这样可以充分利用数据集，避免过拟合，提高模型的泛化能力
交叉验证法的缺点是计算量大，需要多次训练模型，耗时较长
交叉验证法的优点是可以评估模型的泛化能力，避免过拟合
交叉验证法的适用场景是数据量较多，模型训练时间较长，需要多次训练模型

In [27]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris

# 加载数据集
iris = load_iris()
X, y = iris.data, iris.target # 数据集和标签

# 定义模型
# 假设现在有一个模型model
# model 

# 定义K折交叉验证
kf = KFold(n_splits=5)# 5折交叉验证
result = []
# 进行K折交叉验证
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]# 训练集和测试集
    y_train, y_test = y[train_index], y[test_index]# 训练集和测试集的标签
    # print(train_index)    # 输出训练集索引
    print(test_index)     # 输出测试集索引
    # 训练模型
    #model.fit(X_train, y_train)
    
    # 预测测试集
    #y_pred = model.predict(X_test)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

# 自助法
自助法（Bootstrapping）是一种统计学中的方法，它通过随机重采样原始数据集来生成新的样本。
自助法的基本思想是，每次从原始数据集中随机抽取一个样本，并将其加入到新的样本集中，
这样就得到了一个包含原始数据集所有样本的样本集。
重复这个过程，直到得到与原始数据集大小相同的样本集，此时这个样本集就是自助样本集。
自助法的优点是它可以生成与原始数据集大小相同的样本集，并且可以保证每个样本在新样本集中出现的次数与在原始数据集中出现的次数相同。
自助法的缺点是它需要对原始数据集进行多次随机抽样，这可能会增加计算成本。
自助法的应用场景包括：
1. 评估模型泛化能力：通过自助法可以评估模型的泛化能力，  
2. 估计模型参数的置信区间：通过自助法可以估计模型参数的置信区间， 
3. 估计模型参数的标准差：通过自助法可以估计模型参数的标准差， 
4. 估计模型参数的偏差：通过自助法可以估计模型参数的偏差， 
5. 估计模型参数的方差：通过自助法可以估计模型参数的方差，

In [31]:
import numpy as np
from sklearn.utils import resample

#假设有一个数据集X和对应的标签y
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array([0, 1, 0, 1, 0])

#使用自助法进行抽样
bootstrap_samples = []
for _ in range(100):  # 生成10个自助样本
    X_resampled, y_resampled = resample(X, y)# 随机重采样原始数据集，生成新的样本集
    bootstrap_samples.append((X_resampled, y_resampled))# 将生成的自助样本添加到列表中
print(bootstrap_samples)   
#bootstrap_samples现在包含了100个自助样本，每个样本都是原始数据集的一个随机子集

[(array([[ 5,  6],
       [ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [ 1,  2]]), array([0, 0, 0, 0, 0])), (array([[7, 8],
       [3, 4],
       [1, 2],
       [5, 6],
       [1, 2]]), array([1, 1, 0, 0, 0])), (array([[ 7,  8],
       [ 9, 10],
       [ 7,  8],
       [ 9, 10],
       [ 7,  8]]), array([1, 0, 1, 0, 1])), (array([[ 3,  4],
       [ 9, 10],
       [ 3,  4],
       [ 1,  2],
       [ 5,  6]]), array([1, 0, 1, 0, 0])), (array([[1, 2],
       [5, 6],
       [3, 4],
       [1, 2],
       [3, 4]]), array([0, 0, 1, 0, 1])), (array([[ 7,  8],
       [ 9, 10],
       [ 5,  6],
       [ 3,  4],
       [ 7,  8]]), array([1, 0, 0, 1, 1])), (array([[ 5,  6],
       [ 7,  8],
       [ 3,  4],
       [ 1,  2],
       [ 9, 10]]), array([0, 1, 1, 0, 0])), (array([[ 7,  8],
       [ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [ 3,  4]]), array([1, 0, 0, 0, 1])), (array([[ 9, 10],
       [ 5,  6],
       [ 5,  6],
       [ 5,  6],
       [ 5,  6]]), array([0, 0, 0, 0, 0])), (array([[ 9, 10],
       [ 9, 10],
       [ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([0, 0, 0, 0, 0])), (array([[ 5,  6],
       [ 9, 10],
       [ 7,  8],
       [ 9, 10],
       [ 5,  6]]), array([0, 0, 1, 0, 0])), (array([[ 9, 10],
       [ 5,  6],
       [ 3,  4],
       [ 9, 10],
       [ 7,  8]]), array([0, 0, 1, 0, 1])), (array([[ 7,  8],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 7,  8]]), array([1, 0, 1, 0, 1])), (array([[ 7,  8],
       [ 9, 10],
       [ 5,  6],
       [ 5,  6],
       [ 7,  8]]), array([1, 0, 0, 0, 1])), (array([[5, 6],
       [1, 2],
       [7, 8],
       [7, 8],
       [5, 6]]), array([0, 0, 1, 1, 0])), (array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 6],
       [7, 8]]), array([0, 1, 0, 0, 1])), (array([[ 3,  4],
       [ 9, 10],
       [ 1,  2],
       [ 3,  4],
       [ 7,  8]]), array([1, 0, 0, 1, 1])), (array([[1, 2],
       [7, 8],
       [1, 2],
       [7, 8],
       [1, 2]]), array([0, 1, 0, 1, 0])), (array([[5, 6],
       [1, 2],
       [7, 8],
       [3, 4],
       [7, 8]]), array([0, 0, 1, 1, 1])), (array([[ 1,  2],
       [ 1,  2],
       [ 5,  6],
       [ 1,  2],
       [ 9, 10]]), array([0, 0, 0, 0, 0])), (array([[7, 8],
       [1, 2],
       [7, 8],
       [7, 8],
       [3, 4]]), array([1, 0, 1, 1, 1])), (array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [ 3,  4],
       [ 5,  6]]), array([0, 0, 0, 1, 0])), (array([[7, 8],
       [3, 4],
       [1, 2],
       [3, 4],
       [7, 8]]), array([1, 1, 0, 1, 1])), (array([[ 7,  8],
       [ 1,  2],
       [ 3,  4],
       [ 1,  2],
       [ 9, 10]]), array([1, 0, 1, 0, 0])), (array([[ 7,  8],
       [ 9, 10],
       [ 7,  8],
       [ 1,  2],
       [ 9, 10]]), array([1, 0, 1, 0, 0])), (array([[ 1,  2],
       [ 5,  6],
       [ 1,  2],
       [ 3,  4],
       [ 9, 10]]), array([0, 0, 0, 1, 0])), (array([[ 1,  2],
       [ 7,  8],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]]), array([0, 1, 1, 1, 0])), (array([[ 7,  8],
       [ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 5,  6]]), array([1, 1, 0, 0, 0])), (array([[5, 6],
       [7, 8],
       [3, 4],
       [3, 4],
       [7, 8]]), array([0, 1, 1, 1, 1])), (array([[3, 4],
       [3, 4],
       [7, 8],
       [3, 4],
       [3, 4]]), array([1, 1, 1, 1, 1])), (array([[ 5,  6],
       [ 5,  6],
       [ 1,  2],
       [ 9, 10],
       [ 7,  8]]), array([0, 0, 0, 0, 1])), (array([[ 1,  2],
       [ 3,  4],
       [ 9, 10],
       [ 7,  8],
       [ 5,  6]]), array([0, 1, 0, 1, 0])), (array([[ 3,  4],
       [ 9, 10],
       [ 9, 10],
       [ 1,  2],
       [ 9, 10]]), array([1, 0, 0, 0, 0])), (array([[ 9, 10],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10],
       [ 9, 10]]), array([0, 1, 1, 0, 0])), (array([[7, 8],
       [1, 2],
       [1, 2],
       [3, 4],
       [1, 2]]), array([1, 0, 0, 1, 0])), (array([[ 9, 10],
       [ 7,  8],
       [ 1,  2],
       [ 5,  6],
       [ 5,  6]]), array([0, 1, 0, 0, 0])), (array([[ 1,  2],
       [ 9, 10],
       [ 5,  6],
       [ 3,  4],
       [ 9, 10]]), array([0, 0, 0, 1, 0])), (array([[1, 2],
       [7, 8],
       [1, 2],
       [1, 2],
       [3, 4]]), array([0, 1, 0, 0, 1])), (array([[ 1,  2],
       [ 9, 10],
       [ 9, 10],
       [ 7,  8],
       [ 9, 10]]), array([0, 0, 0, 1, 0])), (array([[ 1,  2],
       [ 9, 10],
       [ 9, 10],
       [ 3,  4],
       [ 3,  4]]), array([0, 0, 0, 1, 1])), (array([[3, 4],
       [1, 2],
       [5, 6],
       [5, 6],
       [5, 6]]), array([1, 0, 0, 0, 0])), (array([[ 5,  6],
       [ 3,  4],
       [ 1,  2],
       [ 9, 10],
       [ 3,  4]]), array([0, 1, 0, 0, 1])), (array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 5,  6],
       [ 5,  6]]), array([0, 1, 0, 0, 0])), (array([[5, 6],
       [7, 8],
       [1, 2],
       [7, 8],
       [5, 6]]), array([0, 1, 0, 1, 0])), (array([[ 9, 10],
       [ 3,  4],
       [ 7,  8],
       [ 7,  8],
       [ 1,  2]]), array([0, 1, 1, 1, 0])), (array([[7, 8],
       [3, 4],
       [1, 2],
       [1, 2],
       [5, 6]]), array([1, 1, 0, 0, 0])), (array([[7, 8],
       [7, 8],
       [3, 4],
       [5, 6],
       [5, 6]]), array([1, 1, 1, 0, 0])), (array([[ 9, 10],
       [ 1,  2],
       [ 9, 10],
       [ 3,  4],
       [ 3,  4]]), array([0, 0, 0, 1, 1])), (array([[ 5,  6],
       [ 7,  8],
       [ 3,  4],
       [ 9, 10],
       [ 5,  6]]), array([0, 1, 1, 0, 0])), (array([[ 3,  4],
       [ 5,  6],
       [ 1,  2],
       [ 7,  8],
       [ 9, 10]]), array([1, 0, 0, 1, 0])), (array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [3, 4]]), array([0, 0, 0, 0, 1])), (array([[5, 6],
       [3, 4],
       [5, 6],
       [3, 4],
       [7, 8]]), array([0, 1, 0, 1, 1])), (array([[ 9, 10],
       [ 1,  2],
       [ 1,  2],
       [ 7,  8],
       [ 3,  4]]), array([0, 0, 0, 1, 1])), (array([[ 7,  8],
       [ 1,  2],
       [ 9, 10],
       [ 5,  6],
       [ 7,  8]]), array([1, 0, 0, 0, 1])), (array([[7, 8],
       [3, 4],
       [7, 8],
       [3, 4],
       [3, 4]]), array([1, 1, 1, 1, 1])), (array([[5, 6],
       [1, 2],
       [3, 4],
       [1, 2],
       [1, 2]]), array([0, 0, 1, 0, 0])), (array([[ 7,  8],
       [ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [ 3,  4]]), array([1, 0, 0, 0, 1])), (array([[ 9, 10],
       [ 9, 10],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]]), array([0, 0, 1, 1, 0])), (array([[ 3,  4],
       [ 9, 10],
       [ 5,  6],
       [ 9, 10],
       [ 7,  8]]), array([1, 0, 0, 0, 1])), (array([[ 1,  2],
       [ 3,  4],
       [ 9, 10],
       [ 7,  8],
       [ 7,  8]]), array([0, 1, 0, 1, 1])), (array([[ 5,  6],
       [ 9, 10],
       [ 7,  8],
       [ 3,  4],
       [ 3,  4]]), array([0, 0, 1, 1, 1])), (array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 9, 10],
       [ 5,  6]]), array([0, 1, 0, 0, 0])), (array([[ 9, 10],
       [ 9, 10],
       [ 5,  6],
       [ 5,  6],
       [ 3,  4]]), array([0, 0, 0, 0, 1])), (array([[ 5,  6],
       [ 1,  2],
       [ 7,  8],
       [ 9, 10],
       [ 1,  2]]), array([0, 0, 1, 0, 0])), (array([[5, 6],
       [1, 2],
       [5, 6],
       [5, 6],
       [1, 2]]), array([0, 0, 0, 0, 0])), (array([[ 7,  8],
       [ 7,  8],
       [ 9, 10],
       [ 9, 10],
       [ 5,  6]]), array([1, 1, 0, 0, 0])), (array([[ 5,  6],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 5,  6]]), array([0, 0, 1, 0, 0])), (array([[ 3,  4],
       [ 7,  8],
       [ 9, 10],
       [ 5,  6],
       [ 9, 10]]), array([1, 1, 0, 0, 0])), (array([[ 5,  6],
       [ 5,  6],
       [ 3,  4],
       [ 9, 10],
       [ 5,  6]]), array([0, 0, 1, 0, 0])), (array([[ 9, 10],
       [ 7,  8],
       [ 3,  4],
       [ 3,  4],
       [ 9, 10]]), array([0, 1, 1, 1, 0])), (array([[ 9, 10],
       [ 1,  2],
       [ 9, 10],
       [ 1,  2],
       [ 3,  4]]), array([0, 0, 0, 0, 1])), (array([[ 9, 10],
       [ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 7,  8]]), array([0, 1, 0, 0, 1])), (array([[ 3,  4],
       [ 7,  8],
       [ 3,  4],
       [ 1,  2],
       [ 9, 10]]), array([1, 1, 1, 0, 0])), (array([[ 9, 10],
       [ 7,  8],
       [ 9, 10],
       [ 9, 10],
       [ 5,  6]]), array([0, 1, 0, 0, 0])), (array([[7, 8],
       [3, 4],
       [3, 4],
       [1, 2],
       [5, 6]]), array([1, 1, 1, 0, 0])), (array([[ 3,  4],
       [ 1,  2],
       [ 9, 10],
       [ 7,  8],
       [ 7,  8]]), array([1, 0, 0, 1, 1])), (array([[ 5,  6],
       [ 9, 10],
       [ 5,  6],
       [ 5,  6],
       [ 7,  8]]), array([0, 0, 0, 0, 1])), (array([[ 5,  6],
       [ 3,  4],
       [ 3,  4],
       [ 5,  6],
       [ 9, 10]]), array([0, 1, 1, 0, 0])), (array([[ 5,  6],
       [ 9, 10],
       [ 3,  4],
       [ 1,  2],
       [ 9, 10]]), array([0, 0, 1, 0, 0])), (array([[ 9, 10],
       [ 7,  8],
       [ 7,  8],
       [ 1,  2],
       [ 5,  6]]), array([0, 1, 1, 0, 0])), (array([[ 9, 10],
       [ 1,  2],
       [ 3,  4],
       [ 1,  2],
       [ 7,  8]]), array([0, 0, 1, 0, 1])), (array([[1, 2],
       [5, 6],
       [7, 8],
       [1, 2],
       [5, 6]]), array([0, 0, 1, 0, 0])), (array([[5, 6],
       [3, 4],
       [7, 8],
       [7, 8],
       [1, 2]]), array([0, 1, 1, 1, 0])), (array([[ 3,  4],
       [ 9, 10],
       [ 7,  8],
       [ 9, 10],
       [ 7,  8]]), array([1, 0, 1, 0, 1])), (array([[1, 2],
       [7, 8],
       [3, 4],
       [3, 4],
       [3, 4]]), array([0, 1, 1, 1, 1])), (array([[ 7,  8],
       [ 9, 10],
       [ 5,  6],
       [ 9, 10],
       [ 1,  2]]), array([1, 0, 0, 0, 0])), (array([[5, 6],
       [3, 4],
       [1, 2],
       [5, 6],
       [5, 6]]), array([0, 1, 0, 0, 0])), (array([[7, 8],
       [1, 2],
       [1, 2],
       [7, 8],
       [7, 8]]), array([1, 0, 0, 1, 1])), (array([[ 5,  6],
       [ 7,  8],
       [ 7,  8],
       [ 9, 10],
       [ 5,  6]]), array([0, 1, 1, 0, 0])), (array([[ 9, 10],
       [ 5,  6],
       [ 7,  8],
       [ 7,  8],
       [ 1,  2]]), array([0, 0, 1, 1, 0])), (array([[ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 5,  6],
       [ 7,  8]]), array([1, 0, 0, 0, 1])), (array([[1, 2],
       [5, 6],
       [3, 4],
       [7, 8],
       [7, 8]]), array([0, 0, 1, 1, 1])), (array([[3, 4],
       [5, 6],
       [5, 6],
       [5, 6],
       [5, 6]]), array([1, 0, 0, 0, 0])), (array([[3, 4],
       [7, 8],
       [5, 6],
       [1, 2],
       [7, 8]]), array([1, 1, 0, 0, 1])), (array([[ 9, 10],
       [ 3,  4],
       [ 5,  6],
       [ 3,  4],
       [ 5,  6]]), array([0, 1, 0, 1, 0])), (array([[3, 4],
       [3, 4],
       [7, 8],
       [1, 2],
       [7, 8]]), array([1, 1, 1, 0, 1])), (array([[1, 2],
       [7, 8],
       [1, 2],
       [7, 8],
       [7, 8]]), array([0, 1, 0, 1, 1])), (array([[ 5,  6],
       [ 9, 10],
       [ 3,  4],
       [ 3,  4],
       [ 5,  6]]), array([0, 0, 1, 1, 0])), (array([[ 9, 10],
       [ 1,  2],
       [ 7,  8],
       [ 3,  4],
       [ 3,  4]]), array([0, 0, 1, 1, 1])), (array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 1,  2]]), array([0, 1, 0, 0, 0]))]