In [168]:
import pandas as pd

In [169]:
# 创建字典 
dict_v = { 'a':0, 'b':0.25, 'c':0.5, 'd':0.75, 'e':1 }

In [170]:
# 用字典创建对象 
sr = pd.Series( dict_v ) 
sr

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

数组创建法

In [171]:
# 先定义键与值 
v = [0, 0.25, 0.5, 0.75, 1] 
k = ['a', 'b', 'c', 'd', 'e']

In [172]:
# 用列表创建对象 
sr = pd.Series( v, index=k ) 
sr

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

一维对象的属性   
Series 对象有两个属性：values与index。

In [173]:
# 用数组创建sr 
v = ( [ 53, 64, 72, 82 ] ) 
k = ['1 号', '2 号', '3 号', '4 号'] 
sr = pd.Series( v, index=k ) 
sr

1 号    53
2 号    64
3 号    72
4 号    82
dtype: int64

In [174]:
# 查看values属性 
sr.values

array([53, 64, 72, 82])

In [175]:
# 查看index 属性 
sr.index

Index(['1 号', '2 号', '3 号', '4 号'], dtype='object')

In [176]:
import pandas as pd 
import torch

In [177]:
# 用张量创建sr 
v = torch.tensor( [ 53, 64, 72, 82 ] ) 
k = ['1 号', '2 号', '3 号', '4 号'] 
sr = pd.Series( v, index=k ) 
sr

1 号    53
2 号    64
3 号    72
4 号    82
dtype: int64

In [178]:
# 查看values的属性 
sr.values

array([53, 64, 72, 82])

In [179]:
# 创建sr1:人的年龄
v1 = [ 53, 64, 72, 82 ] 
i = [ '1 号', '2 号', '3 号', '4 号' ] 
sr1 = pd.Series( v1, index=i ) 
sr1

1 号    53
2 号    64
3 号    72
4 号    82
dtype: int64

In [180]:
# 创建sr2：人的性别 
v2 = [ '女', '男', '男', '女' ] 
i = [ '1 号', '2 号', '3 号', '4 号' ] 
sr2 = pd.Series( v2, index=i ) 
sr2

1 号    女
2 号    男
3 号    男
4 号    女
dtype: object

In [181]:
# 创建df对象 
df = pd.DataFrame( { '年龄':sr1, '性别':sr2 } ) 
df

     年龄 性别
1 号  53  女
2 号  64  男
3 号  72  男
4 号  82  女

In [182]:
# 设定键值 
import numpy as np 
v = np.array( [ [53, '女'], [64, '男'], [72, '男'], [82, '女'] ] ) 
i = [ '1 号', '2 号', '3 号', '4 号' ] 
c = [ '年龄', '性别' ]

In [183]:
# 数组创建法 
df = pd.DataFrame( v, index=i, columns=c ) 
df

     年龄 性别
1 号  53  女
2 号  64  男
3 号  72  男
4 号  82  女

二维对象的属性   
DataFrame 对象有三个属性：values、index与columns。

In [184]:
# 设定键值 
v = [ [53, '女'], [64, '男'], [72, '男'], [82, '女'] ] 
i = [ '1 号', '2 号', '3 号', '4 号' ] 
c = [ '年龄', '性别' ]

In [185]:
# 数组创建法 
df = pd.DataFrame( v, index=i, columns=c ) 
df

     年龄 性别
1 号  53  女
2 号  64  男
3 号  72  男
4 号  82  女

In [186]:
# 查看index 属性 
df.index

Index(['1 号', '2 号', '3 号', '4 号'], dtype='object')

In [187]:
# 查看columns属性 
df.columns

Index(['年龄', '性别'], dtype='object')

In [188]:
# 提取完整的数组 
arr = df.values 
print(arr)

[[53 '女']
 [64 '男']
 [72 '男']
 [82 '女']]

Pandas 的索引分为显式索引与隐式索引。显式索引是使用Pandas对象提
供的索引，而隐式索引是使用数组本身自带的从0开始的索引。    
现假设某演示代码中的索引是整数，这个时候显式索引和隐式索引可能
会出乱子。于是，Pandas 作者发明了索引器loc（显式）与iloc（隐式），
手动告诉程序自己这句话是显式索引还是隐式索引。

In [189]:
# 创建sr 
v = [ 53, 64, 72, 82 ] 
k = ['1 号', '2 号', '3 号', '4 号'] 
sr = pd.Series( v, index=k ) 
sr

1 号    53
2 号    64
3 号    72
4 号    82
dtype: int64

In [190]:
# 访问元素 
sr.loc[ '3 号' ]

np.int64(72)

In [191]:
# 访问元素 
sr.iloc[ 2 ]

np.int64(72)

In [192]:
# 创建畸形df 
v = [ [53, 64, 72, 82], [ '女', '男', '男', '女' ] ] 
i = [ '年龄', '性别' ] 
c = [ '1号', '2号', '3号', '4号' ] 
df = pd.DataFrame( v, index=i, columns=c ) 
df

    1号  2号  3号  4号
年龄  53  64  72  82
性别   女   男   男   女

In [193]:
# 转置 
df = df.T 
df

    年龄 性别
1号  53  女
2号  64  男
3号  72  男
4号  82  女

In [194]:
# 左右翻转 
df = df.iloc[ : , : : -1 ] 
df

   性别  年龄
1号  女  53
2号  男  64
3号  男  72
4号  女  82

In [195]:
# 上下翻转 
df = df.iloc[ : : -1 , : ] 
df

   性别  年龄
4号  女  82
3号  男  72
2号  男  64
1号  女  53

In [196]:
# 数组法创建sr 
i = [ '1号', '2号', '3号', '4号' ] 
v1 = [ 10, 20, 30, 40 ] 
v2 = [ '女', '男', '男', '女' ] 
v3 = [ 1, 2, 3, 4 ] 
sr1 = pd.Series( v1, index=i ) 
sr2 = pd.Series( v2, index=i ) 
sr3 = pd.Series( v3, index=i ) 
sr1, sr2, sr3

(1号    10
 2号    20
 3号    30
 4号    40
 dtype: int64,
 1号    女
 2号    男
 3号    男
 4号    女
 dtype: object,
 1号    1
 2号    2
 3号    3
 4号    4
 dtype: int64)

In [197]:
# 字典法创建df 
df = pd.DataFrame( { '年龄':sr1, '性别':sr2 } ) 
df

    年龄 性别
1号  10  女
2号  20  男
3号  30  男
4号  40  女

In [198]:
# 把sr并入df中 
df['牌照'] = sr3 
df

    年龄 性别  牌照
1号  10  女   1
2号  20  男   2
3号  30  男   3
4号  40  女   4

In [199]:
# 创建sr1和sr2 
v1 = [10, 20, 30, 40] 
v2 = [40, 50, 60] 
k1 = [ '1号', '2号', '3号', '4号' ] 
k2 = [ '4号', '5号', '6号' ] 
sr1 = pd.Series( v1, index= k1 ) 
sr2 = pd.Series( v2, index= k2 ) 
sr1, sr2

(1号    10
 2号    20
 3号    30
 4号    40
 dtype: int64,
 4号    40
 5号    50
 6号    60
 dtype: int64)

In [200]:
# 合并 
pd.concat( [sr1, sr2] )

1号    10
2号    20
3号    30
4号    40
4号    40
5号    50
6号    60
dtype: int64

可见pandas中可以重复

In [201]:
# 设定df1、df2、df3 
v1 = [ [10, '女'], [20, '男'], [30, '男'], [40, '女'] ] 
v2 = [ [1, '是'], [2, '是'], [3, '是'], [4, '否'] ] 
v3 = [ [50, '男', 5, '是'], [60, '女', 6, '是'] ] 
i1 = [ '1 号', '2 号', '3 号', '4 号' ] 
i2 = [ '1 号', '2 号', '3 号', '4 号' ] 
i3 = [ '5 号', '6 号' ] 
c1 = [ '年龄', '性别' ] 
c2 = [ '牌照', 'ikun' ] 
c3 = [ '年龄', '性别', '牌照', 'ikun' ] 
df1 = pd.DataFrame( v1, index=i1, columns=c1 ) 
df2 = pd.DataFrame( v2, index=i2, columns=c2 ) 
df3 = pd.DataFrame( v3, index=i3, columns=c3 ) 
print( df1 )
print( df2 )
print( df3 )

     年龄 性别
1 号  10  女
2 号  20  男
3 号  30  男
4 号  40  女
     牌照 ikun
1 号   1    是
2 号   2    是
3 号   3    是
4 号   4    否
     年龄 性别  牌照 ikun
5 号  50  男   5    是
6 号  60  女   6    是

In [202]:
# 合并列对象（添加列特征） 
df = pd.concat( [df1,df2], axis=1 ) 
df

     年龄 性别  牌照 ikun
1 号  10  女   1    是
2 号  20  男   2    是
3 号  30  男   3    是
4 号  40  女   4    否

In [203]:
# 创建sr 
v = [ 53, None, 72, 82 ] 
k = ['1号', '2号', '3号', '4号'] 
sr = pd.Series( v, index=k ) 
sr

1号    53.0
2号     NaN
3号    72.0
4号    82.0
dtype: float64

In [204]:
# 创建df 
v = [ [None, 1], [64, None], [72, 3], [82, 4] ] 
i = [ '1号', '2号', '3号', '4号' ] 
c = [ '年龄', '牌照' ] 
df = pd.DataFrame( v, index=i, columns=c ) 
df

      年龄   牌照
1号   NaN  1.0
2号  64.0  NaN
3号  72.0  3.0
4号  82.0  4.0

In [205]:
# 发现sr的缺失值 
sr.isnull()

1号    False
2号     True
3号    False
4号    False
dtype: bool

In [206]:
# 发现df的缺失值 
df.isnull()
# 可以用‘~’非号取反

       年龄     牌照
1号   True  False
2号  False   True
3号  False  False
4号  False  False

In [207]:
# 剔除sr的缺失值 
sr.dropna()

1号    53.0
3号    72.0
4号    82.0
dtype: float64

In [208]:
# 剔除df含缺失值的行 
df.dropna()

      年龄   牌照
3号  72.0  3.0
4号  82.0  4.0

In [209]:
# 剔除df全是NaN的个体 ，否则保留
df.dropna(how='all')

      年龄   牌照
1号   NaN  1.0
2号  64.0  NaN
3号  72.0  3.0
4号  82.0  4.0

In [210]:
# 创建sr ，有空缺值
v = [ 53, None, 72, 82 ]  
sr = pd.Series( v, index=['1 号', '2 号', '3 号', '4 号'] ) 
sr

1 号    53.0
2 号     NaN
3 号    72.0
4 号    82.0
dtype: float64

In [211]:
# 用常数（0）填充 
sr.fillna(0)

1 号    53.0
2 号     0.0
3 号    72.0
4 号    82.0
dtype: float64

In [212]:
# 用常数（均值）填充 
import numpy as np 
sr.fillna(np.mean(sr))

1 号    53.0
2 号    69.0
3 号    72.0
4 号    82.0
dtype: float64

# Excel
首先，创建Excel文件，录入信息，第一列为index，第一行为columns    
接着，将其另存为为CSV文件，无视之后弹出的“工作薄的部分功能丢失”的提示   
最后，使用pandas读取CSV文件，并将index和columns设置为第一行和第一列

In [213]:
# 导入Pandas对象 
df = pd.read_csv('Data.csv', index_col=0) 
df

     age gender  num kun
1号  10.0      女    1   是
2号  20.0      男    2   是
3号  30.0      男    3   是
4号  40.0      女    4   否
5号  50.0      男    5   是
6号  60.0      女    6   是

In [214]:
# 导入Pandas对象 
pd.read_csv('行星数据.csv', index_col=0)

      发现时间  发现数量   观测方法    行星质量     距地距离     轨道周期
0     1989     1   径向速度  11.680    40.57  83.8880
1     1992     3  脉冲星计时     NaN      NaN  25.2620
2     1992     3  脉冲星计时     NaN      NaN  66.5419
3     1994     3  脉冲星计时     NaN      NaN  98.2114
4     1995     1   径向速度   0.472    15.36   4.2308
...    ...   ...    ...     ...      ...      ...
1030  2014     1     凌日     NaN      NaN   2.4650
1031  2014     1     凌日     NaN      NaN  68.9584
1032  2014     1     凌日     NaN  1056.00   1.7209
1033  2014     1     凌日     NaN      NaN  66.2620
1034  2014     1     凌日     NaN   470.00   0.9255

[1035 rows x 6 columns]

In [215]:
# 导入Pandas对象 
df = pd.read_csv('行星数据.csv', index_col=0) 
df.head()# 仅输出前五行
df.tail()# 仅输出后五行

      发现时间  发现数量 观测方法  行星质量    距地距离     轨道周期
1030  2014     1   凌日   NaN     NaN   2.4650
1031  2014     1   凌日   NaN     NaN  68.9584
1032  2014     1   凌日   NaN  1056.0   1.7209
1033  2014     1   凌日   NaN     NaN  66.2620
1034  2014     1   凌日   NaN   470.0   0.9255

In [216]:
# 最大值函数 np.max( ) 
df.max()

发现时间        2014
发现数量           7
观测方法      轨道亮度调制
行星质量        25.0
距地距离      8500.0
轨道周期    730000.0
dtype: object

In [217]:
df.describe()

              发现时间         发现数量        行星质量         距地距离           轨道周期
count  1035.000000  1035.000000  513.000000   808.000000     992.000000
mean   2009.070531     1.785507    2.638161   264.069282    2002.917596
std       3.972567     1.240976    3.818617   733.116493   26014.728304
min    1989.000000     1.000000    0.003600     1.350000       0.090700
25%    2007.000000     1.000000    0.229000    32.560000       5.442575
50%    2010.000000     1.000000    1.260000    55.250000      39.979500
75%    2012.000000     2.000000    3.040000   178.500000     526.005000
max    2014.000000     7.000000   25.000000  8500.000000  730000.000000

第1行count是计数项，统计每个特征的有效数量（即排除缺失值），从count
可以看出，行星质量的缺失值比较多，需要考虑一定的办法填充或舍弃。   
第2行至第3行的mean与std统计每列特征的均值与标准差。   
第4行至第8行的min、25%、50%、75%、max的意思是五个分位点，即
把数组从小到大排序后，0%、25%、50%、75%、100%五个位置上的数值的取值。
显然，50%分位点即中位数。

# 两个特征内的数据透视

In [218]:
# 导入Pandas对象 
df = pd.read_csv('泰坦尼克.csv', index_col=0) 
df.head()

  性别    年龄 船舱等级       费用  是否生还
0  男  22.0   三等   7.2500     0
1  女  38.0   一等  71.2833     1
2  女  26.0   三等   7.9250     1
3  女  35.0   一等  53.1000     1
4  男  35.0   三等   8.0500     0

In [219]:
# 一个特征：性别 
df.pivot_table('是否生还', index='性别')

        是否生还
性别
女   0.742038
男   0.188908

In [220]:
# 两个特征：性别、船舱等级 
df.pivot_table('是否生还', index='性别', columns='船舱等级')

船舱等级        一等        三等        二等
性别
女     0.968085  0.500000  0.921053
男     0.368852  0.135447  0.157407

值得注意的是，pivot_table() 方法有一个很重要的参数：aggfunc，其默认值
是'mean'，除此以外，所有的聚合函数 'max'、'min'、'sum'、'count' 均可使用。

In [221]:
# 三个特征：性别、船舱等级、年龄 
age = pd.cut( df['年龄'], [0,18,120] )    # 以18岁为分水岭 
df.pivot_table('是否生还', index= ['性别', age], columns='船舱等级')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_16244\647271224.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table('是否生还', index= ['性别', age], columns='船舱等级')

船舱等级                一等        三等        二等
性别 年龄
女  (0, 18]    0.909091  0.511628  1.000000
   (18, 120]  0.972973  0.423729  0.900000
男  (0, 18]    0.800000  0.215686  0.600000
   (18, 120]  0.375000  0.133663  0.071429

In [222]:
# 四个特征：性别、船舱等级、年龄、费用 
fare = pd.qcut( df['费用'], 2 )       # 将费用自动分为两部分 
df.pivot_table('是否生还', index= ['船舱等级',fare], columns=['性别', age])

C:\Users\Administrator\AppData\Local\Temp\ipykernel_16244\1530435932.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table('是否生还', index= ['船舱等级',fare], columns=['性别', age])

性别                             女                   男
年龄                       (0, 18] (18, 120]   (0, 18] (18, 120]
船舱等级 费用
一等   (-0.001, 14.454]        NaN       NaN       NaN  0.000000
     (14.454, 512.329]  0.909091  0.972973  0.800000  0.391304
三等   (-0.001, 14.454]   0.714286  0.444444  0.260870  0.125000
     (14.454, 512.329]  0.318182  0.391304  0.178571  0.192308
二等   (-0.001, 14.454]   1.000000  0.880000  0.000000  0.098039
     (14.454, 512.329]  1.000000  0.914286  0.818182  0.030303

pd.cut是手动分割   
pd.qcut是自动分割